### PR TITLE
Fix filtering node_modules and .git dirs

### LINKED ISSUE #21: Not filtering node_modules and .git directories
When using version 5.1.0 (and probably previous versions), tool is not filtering `node_modules` nor `.git` directories out.

It's related to dependency `@nodelib/fs.walk@1.2.6`, there is no filter option, but [`deepFilter`](https://github.com/nodelib/nodelib/tree/@nodelib/fs.walk@1.2.6/packages/fs/fs.walk#deepfilter).

See PR https://github.com/beaugunderson/codeowners/pull/20

### PR DESCRIPTION
**Pull request by yorch**
According to v1.2.6, `filter` option is named `deepFilter`: https://github.com/nodelib/nodelib/tree/@nodelib/fs.walk@1.2.6/packages/fs/fs.walk#deepfilter.

Fixes #21

### CODE REVIEW

**Comment by beaugunderson** [comment]
ah, sorry for the oversight when migrating!

I need to get some unit tests sorted...

**Comment by beaugunderson** [comment]
ah, still needs some work... `entry.path` is the full path, e.g. `/Users/beau/p/codeowners/.git/refs/heads`

will work this out locally, or if you want to open another PR you may beat me to it :)

**Comment by yorch** [comment]
@beaugunderson oh really, `nodelib` need to update their example / doc then lol.. will look at it tonight, thanks

**Comment by beaugunderson** [comment]
fixed and released in 5.1.1 btw

**Pull request merged**
